#启动一个有 go 语言环境的容器
language: go

#go 版本
go:
  - "1.8" 
  
  
install:
  # 安装最新的hugo
  - wget https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_0.51_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  
  
# 运行hugo命令
script:
  - hugo

deploy:
  #指定这是一份github pages的部署配置
  provider: pages
  
  skip_cleanup: true
  
  # token is set in travis-ci.org dashboard
  github_token: $GITHUB_TOKEN
  
  on:
    branch: master
    
  local_dir: public
  
  #github pages rep
  repo: zzzzzip/zzzzzip.githu.io
  
  #branch
  target_branch: master
  email: deploy@travis-ci.org
  name: deployment-bot
