#启动一个有 go 语言环境的容器
language: go

#go 版本
go:
  - "1.8" 
  
#在容器内用 go get 安装 Hugo
install: go get -v github.com/spf13/hugo

# 运行hugo命令
script:
  - hugo

deploy:
  #指定这是一份github pages的部署配置
  provider: pages
  
  skip_cleanup: true
  
  # token is set in travis-ci.org dashboard
  github_token: $GITHUB_TOKEN
  
  on:
    branch: master
    
  local_dir: public
  
  #github pages rep
  repo: zzzzzip/zzzzzip.githu.io
  
  #branch
  target_branch: master
  email: deploy@travis-ci.org
  name: deployment-bot
