name: Deploy GitHub Pages

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - master

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Pull
        uses: edte/blog-by-hugo
        with:
          persist-credentials: false

      # 生成静态文件
      - name: Build
        run: |
            wget https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_0.51_Linux-64bit.deb
            sudo dpkg -i hugo*.deb
            hugo

      # 部署到 GitHub Pages
      - name: Push
        uses: edte/edte.github.io
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master
